### ISSUE TITLE
bump use-kubelogin to v1.2

### ISSUE THREAD

**Issue by Glenn-Terjesen** [entur/gha-meta#39]
https://github.com/entur/gha-meta/blob/dbc236f7724633741e8b8947450e1c704b601c90/.github/actions/k8s-auth/action.yml#L82C13-L82C32

https://github.com/Azure/use-kubelogin/releases/tag/v1.2

**Comment by Glenn-Terjesen** [comment]
node-16 deprecation

**Comment by bvestli** [comment]
The configuration uses `azure/use-kubelogin@v1`, so version 1.2 is already being used
